version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./init-mongodb/data:/tmp/data
    ports:
      - 21021:27017

  redis:
    image: redis:3-alpine
    ports:
      - 21022:6379
